export const SUPPORTED_LANGUAGES = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
] as const;

export type Locale = (typeof SUPPORTED_LANGUAGES)[number]["code"];

export type CatalogEntry = {
  key: string;
  category: "Navigation" | "Common" | "Authentication" | "Pages" | "Payments" | "Contracts" | "PDF";
  khmer: string;
};

export const LANGUAGE_CATALOG: CatalogEntry[] = [
  { key: "Dashboard", category: "Navigation", khmer: "ផ្ទាំងគ្រប់គ្រង" },
  { key: "Apartments", category: "Navigation", khmer: "អគារជួល" },
  { key: "Utilities", category: "Navigation", khmer: "ទឹក និងអគ្គិសនី" },
  { key: "Payments", category: "Navigation", khmer: "ការទូទាត់" },
  { key: "Activity log", category: "Navigation", khmer: "កំណត់ហេតុសកម្មភាព" },
  { key: "Facilities", category: "Navigation", khmer: "បរិក្ខារ" },
  { key: "Utility rates", category: "Navigation", khmer: "តម្លៃទឹក និងអគ្គិសនី" },
  { key: "Contract template", category: "Navigation", khmer: "គំរូកិច្ចសន្យា" },
  { key: "Workspaces", category: "Navigation", khmer: "កន្លែងធ្វើការ" },
  { key: "Users", category: "Navigation", khmer: "អ្នកប្រើប្រាស់" },
  { key: "Currency", category: "Navigation", khmer: "រូបិយប័ណ្ណ" },
  { key: "Payment methods", category: "Navigation", khmer: "វិធីទូទាត់" },
  { key: "Roles & permissions", category: "Navigation", khmer: "តួនាទី និងសិទ្ធិ" },
  { key: "Backup & restore", category: "Navigation", khmer: "បម្រុងទុក និងស្តារឡើងវិញ" },
  { key: "My access", category: "Navigation", khmer: "សិទ្ធិរបស់ខ្ញុំ" },
  { key: "Languages", category: "Navigation", khmer: "ភាសា" },
  { key: "Language", category: "Common", khmer: "ភាសា" },
  { key: "English", category: "Common", khmer: "អង់គ្លេស" },
  { key: "Khmer", category: "Common", khmer: "ខ្មែរ" },
  { key: "Save changes", category: "Common", khmer: "រក្សាទុកការផ្លាស់ប្តូរ" },
  { key: "Saving…", category: "Common", khmer: "កំពុងរក្សាទុក…" },
  { key: "Save", category: "Common", khmer: "រក្សាទុក" },
  { key: "Cancel", category: "Common", khmer: "បោះបង់" },
  { key: "Delete", category: "Common", khmer: "លុប" },
  { key: "Edit", category: "Common", khmer: "កែប្រែ" },
  { key: "Add", category: "Common", khmer: "បន្ថែម" },
  { key: "Create", category: "Common", khmer: "បង្កើត" },
  { key: "Update", category: "Common", khmer: "ធ្វើបច្ចុប្បន្នភាព" },
  { key: "Search", category: "Common", khmer: "ស្វែងរក" },
  { key: "Filter", category: "Common", khmer: "តម្រង" },
  { key: "All", category: "Common", khmer: "ទាំងអស់" },
  { key: "Active", category: "Common", khmer: "សកម្ម" },
  { key: "Inactive", category: "Common", khmer: "អសកម្ម" },
  { key: "Status", category: "Common", khmer: "ស្ថានភាព" },
  { key: "Name", category: "Common", khmer: "ឈ្មោះ" },
  { key: "Email", category: "Common", khmer: "អ៊ីមែល" },
  { key: "Password", category: "Common", khmer: "ពាក្យសម្ងាត់" },
  { key: "Phone", category: "Common", khmer: "លេខទូរស័ព្ទ" },
  { key: "Address", category: "Common", khmer: "អាសយដ្ឋាន" },
  { key: "Description", category: "Common", khmer: "ការពិពណ៌នា" },
  { key: "Notes", category: "Common", khmer: "កំណត់សម្គាល់" },
  { key: "Date", category: "Common", khmer: "កាលបរិច្ឆេទ" },
  { key: "Actions", category: "Common", khmer: "សកម្មភាព" },
  { key: "No results", category: "Common", khmer: "គ្មានលទ្ធផល" },
  { key: "Previous page", category: "Common", khmer: "ទំព័រមុន" },
  { key: "Next page", category: "Common", khmer: "ទំព័របន្ទាប់" },
  { key: "Rows per page", category: "Common", khmer: "ចំនួនជួរក្នុងមួយទំព័រ" },
  { key: "Upload", category: "Common", khmer: "ផ្ទុកឡើង" },
  { key: "Download", category: "Common", khmer: "ទាញយក" },
  { key: "Backup", category: "Common", khmer: "បម្រុងទុក" },
  { key: "Restore backup", category: "Common", khmer: "ស្តារឯកសារបម្រុងទុក" },
  { key: "Restore", category: "Common", khmer: "ស្តារឡើងវិញ" },
  { key: "Restoring…", category: "Common", khmer: "កំពុងស្តារឡើងវិញ…" },
  { key: "Cancel file selection", category: "Common", khmer: "បោះបង់ការជ្រើសរើសឯកសារ" },
  { key: "Restore language pack", category: "Common", khmer: "ស្តារកញ្ចប់ភាសា" },
  { key: "Backup language pack", category: "Common", khmer: "បម្រុងទុកកញ្ចប់ភាសា" },
  { key: "Sign in", category: "Authentication", khmer: "ចូលប្រើ" },
  { key: "Signing in…", category: "Authentication", khmer: "កំពុងចូលប្រើ…" },
  { key: "Sign out", category: "Authentication", khmer: "ចាកចេញ" },
  { key: "Continue", category: "Authentication", khmer: "បន្ត" },
  { key: "Use a different account", category: "Authentication", khmer: "ប្រើគណនីផ្សេង" },
  { key: "Platform Super Admin", category: "Authentication", khmer: "អ្នកគ្រប់គ្រងប្រព័ន្ធកម្រិតខ្ពស់" },
  { key: "Remember this as my default workspace", category: "Authentication", khmer: "ចងចាំជាកន្លែងធ្វើការលំនាំដើម" },
  { key: "Sign in to manage your rental properties", category: "Authentication", khmer: "ចូលប្រើដើម្បីគ្រប់គ្រងអចលនទ្រព្យជួលរបស់អ្នក" },
  {
    key: "This email is used in more than one place. Continue as:",
    category: "Authentication",
    khmer: "អ៊ីមែលនេះត្រូវបានប្រើនៅច្រើនកន្លែង។ បន្តជា៖",
  },
  { key: "Overview of your rental properties", category: "Pages", khmer: "ទិដ្ឋភាពទូទៅនៃអចលនទ្រព្យជួលរបស់អ្នក" },
  { key: "All apartment buildings and their rooms", category: "Pages", khmer: "អគារជួល និងបន្ទប់ទាំងអស់" },
  { key: "Monthly water & electricity meter readings", category: "Pages", khmer: "កំណត់ត្រាកុងទ័រទឹក និងអគ្គិសនីប្រចាំខែ" },
  { key: "Rent + utility invoices, filterable by status/room/month", category: "Pages", khmer: "វិក្កយបត្រថ្លៃជួល និងទឹកភ្លើង អាចត្រងតាមស្ថានភាព បន្ទប់ និងខែ" },
  { key: "Room amenities available for selection", category: "Pages", khmer: "បរិក្ខារបន្ទប់ដែលអាចជ្រើសរើសបាន" },
  { key: "Manage user accounts and roles (administrator only)", category: "Pages", khmer: "គ្រប់គ្រងគណនី និងតួនាទីអ្នកប្រើប្រាស់ (សម្រាប់អ្នកគ្រប់គ្រង)" },
  { key: "New apartment", category: "Pages", khmer: "បន្ថែមអគារជួល" },
  { key: "New workspace", category: "Pages", khmer: "បង្កើតកន្លែងធ្វើការ" },
  { key: "Record utility reading", category: "Pages", khmer: "កត់ត្រាកុងទ័រទឹក និងអគ្គិសនី" },
  { key: "Setup wizard", category: "Pages", khmer: "ការរៀបចំប្រព័ន្ធ" },
  { key: "Room", category: "Payments", khmer: "បន្ទប់" },
  { key: "Apartment", category: "Payments", khmer: "អគារ" },
  { key: "Month", category: "Payments", khmer: "ខែ" },
  { key: "Amount", category: "Payments", khmer: "ចំនួនទឹកប្រាក់" },
  { key: "Pending", category: "Payments", khmer: "កំពុងរង់ចាំ" },
  { key: "Paid", category: "Payments", khmer: "បានទូទាត់" },
  { key: "Overdue", category: "Payments", khmer: "ហួសកំណត់" },
  { key: "Mark paid", category: "Payments", khmer: "កត់ត្រាថាបានទូទាត់" },
  { key: "Print PDF", category: "Payments", khmer: "បោះពុម្ព PDF" },
  { key: "Share image", category: "Payments", khmer: "ចែករំលែករូបភាព" },
  { key: "Contract", category: "Contracts", khmer: "កិច្ចសន្យា" },
  { key: "Start contract", category: "Contracts", khmer: "ចាប់ផ្តើមកិច្ចសន្យា" },
  { key: "Review contract", category: "Contracts", khmer: "ពិនិត្យកិច្ចសន្យា" },
  { key: "Contract agreement", category: "Contracts", khmer: "កិច្ចព្រមព្រៀងជួល" },
  { key: "Open in new tab", category: "Contracts", khmer: "បើកក្នុងផ្ទាំងថ្មី" },
  { key: "Tenant name", category: "Contracts", khmer: "ឈ្មោះអ្នកជួល" },
  { key: "Start date", category: "Contracts", khmer: "ថ្ងៃចាប់ផ្តើម" },
  { key: "End date", category: "Contracts", khmer: "ថ្ងៃបញ្ចប់" },
  { key: "Monthly rent", category: "Contracts", khmer: "ថ្លៃជួលប្រចាំខែ" },
  { key: "Security deposit", category: "Contracts", khmer: "ប្រាក់កក់" },
  { key: "PAYMENT RECEIPT", category: "PDF", khmer: "បង្កាន់ដៃទូទាត់" },
  { key: "PAYMENT INVOICE", category: "PDF", khmer: "វិក្កយបត្រទូទាត់" },
  { key: "PAID", category: "PDF", khmer: "បានទូទាត់" },
  { key: "PENDING", category: "PDF", khmer: "កំពុងរង់ចាំ" },
  { key: "OVERDUE", category: "PDF", khmer: "ហួសកំណត់" },
  { key: "Generated on {date}", category: "PDF", khmer: "បានបង្កើតនៅថ្ងៃទី {date}" },
  { key: "Billed to", category: "PDF", khmer: "ចេញវិក្កយបត្រជូន" },
  { key: "Invoice #", category: "PDF", khmer: "លេខវិក្កយបត្រ" },
  { key: "Billing period", category: "PDF", khmer: "រយៈពេលគិតថ្លៃ" },
  { key: "Due date", category: "PDF", khmer: "ថ្ងៃផុតកំណត់" },
  { key: "Charges", category: "PDF", khmer: "ថ្លៃសេវា" },
  { key: "Rent", category: "PDF", khmer: "ថ្លៃជួល" },
  { key: "Utilities (water & electricity)", category: "PDF", khmer: "ទឹក និងអគ្គិសនី" },
  { key: "Total due: {amount}", category: "PDF", khmer: "សរុបត្រូវបង់៖ {amount}" },
  { key: "Paid on", category: "PDF", khmer: "បានទូទាត់នៅថ្ងៃទី" },
  { key: "Amount paid", category: "PDF", khmer: "ចំនួនបានទូទាត់" },
  { key: "Paid via", category: "PDF", khmer: "ទូទាត់តាម" },
  { key: "Ways to Pay", category: "PDF", khmer: "វិធីទូទាត់" },
  { key: "Bank / provider", category: "PDF", khmer: "ធនាគារ / ក្រុមហ៊ុនផ្តល់សេវា" },
  { key: "Account holder", category: "PDF", khmer: "ម្ចាស់គណនី" },
  { key: "Account / phone number", category: "PDF", khmer: "លេខគណនី / ទូរស័ព្ទ" },
  { key: "Scan to pay", category: "PDF", khmer: "ស្កេនដើម្បីទូទាត់" },
  { key: "Utility reading QR codes", category: "PDF", khmer: "កូដ QR សម្រាប់កត់ត្រាទឹក និងអគ្គិសនី" },
  { key: "Scan to record this room's meter reading", category: "PDF", khmer: "ស្កេនដើម្បីកត់ត្រាលេខកុងទ័ររបស់បន្ទប់នេះ" },
  { key: "Page {current} of {total}", category: "PDF", khmer: "ទំព័រ {current} នៃ {total}" },
  { key: "RESIDENTIAL RENTAL AGREEMENT", category: "PDF", khmer: "កិច្ចព្រមព្រៀងជួលលំនៅឋាន" },
  { key: "PREVIEW — this contract has not been started yet", category: "PDF", khmer: "មើលជាមុន — កិច្ចសន្យានេះមិនទាន់បានចាប់ផ្តើមទេ" },
  { key: "Prepared on {date}", category: "PDF", khmer: "រៀបចំនៅថ្ងៃទី {date}" },
  { key: "LANDLORD / PROPERTY MANAGER", category: "PDF", khmer: "ម្ចាស់ផ្ទះ / អ្នកគ្រប់គ្រងអចលនទ្រព្យ" },
  { key: "TENANT", category: "PDF", khmer: "អ្នកជួល" },
  { key: "Signature", category: "PDF", khmer: "ហត្ថលេខា" },
  { key: "Printed name: {name}", category: "PDF", khmer: "ឈ្មោះ៖ {name}" },
  { key: "Date: _______________________", category: "PDF", khmer: "កាលបរិច្ឆេទ៖ _______________________" },
  { key: "Draft preview", category: "PDF", khmer: "សេចក្តីព្រាង" },
  { key: "Contract {id}", category: "PDF", khmer: "កិច្ចសន្យា {id}" },
  { key: "Generated {date}", category: "PDF", khmer: "បានបង្កើត {date}" },
  { key: "Parties", category: "PDF", khmer: "ភាគីនៃកិច្ចសន្យា" },
  { key: "Landlord", category: "PDF", khmer: "ម្ចាស់ផ្ទះ" },
  { key: "Tenant", category: "PDF", khmer: "អ្នកជួល" },
  { key: "Tenant phone", category: "PDF", khmer: "លេខទូរស័ព្ទអ្នកជួល" },
  { key: "Tenant email", category: "PDF", khmer: "អ៊ីមែលអ្នកជួល" },
  { key: "Tenant ID number", category: "PDF", khmer: "លេខអត្តសញ្ញាណអ្នកជួល" },
  { key: "Number of occupants", category: "PDF", khmer: "ចំនួនអ្នកស្នាក់នៅ" },
  { key: "Property", category: "PDF", khmer: "អចលនទ្រព្យ" },
  { key: "Floor", category: "PDF", khmer: "ជាន់" },
  { key: "Size", category: "PDF", khmer: "ទំហំ" },
  { key: "Facilities included", category: "PDF", khmer: "បរិក្ខាររួមបញ្ចូល" },
  { key: "Lease Term", category: "PDF", khmer: "រយៈពេលជួល" },
  { key: "Rent & Deposit", category: "PDF", khmer: "ថ្លៃជួល និងប្រាក់កក់" },
  { key: "Water meter reading at move-in", category: "PDF", khmer: "លេខកុងទ័រទឹកពេលចូលស្នាក់នៅ" },
  { key: "Electricity meter reading at move-in", category: "PDF", khmer: "លេខកុងទ័រអគ្គិសនីពេលចូលស្នាក់នៅ" },
  { key: "Use of Premises", category: "PDF", khmer: "ការប្រើប្រាស់ទីតាំង" },
  { key: "Maintenance & Repairs", category: "PDF", khmer: "ការថែទាំ និងជួសជុល" },
  { key: "Termination", category: "PDF", khmer: "ការបញ្ចប់កិច្ចសន្យា" },
  { key: "Additional Notes", category: "PDF", khmer: "កំណត់សម្គាល់បន្ថែម" },
  { key: "Governing Terms", category: "PDF", khmer: "លក្ខខណ្ឌគ្រប់គ្រង" },
  {
    key: "This is a general lease template generated from the details entered in RentalHRM. It does not constitute legal advice — review it (and local rental regulations) before relying on it.",
    category: "PDF",
    khmer: "នេះជាគំរូកិច្ចសន្យាជួលទូទៅដែលបង្កើតពីព័ត៌មានក្នុង RentalHRM។ វាមិនមែនជាការប្រឹក្សាផ្នែកច្បាប់ទេ — សូមពិនិត្យកិច្ចសន្យា និងបទប្បញ្ញត្តិជួលក្នុងតំបន់មុនពេលប្រើប្រាស់។",
  },
  {
    key: "Rent is due in full on or before the last day of each calendar month. The security deposit is refundable at the end of the lease, less any deductions for unpaid rent, unpaid utility charges, or damage beyond normal wear and tear.",
    category: "PDF",
    khmer: "ថ្លៃជួលត្រូវបង់ពេញចំនួននៅថ្ងៃចុងក្រោយនៃខែនីមួយៗ ឬមុននោះ។ ប្រាក់កក់នឹងត្រូវប្រគល់ជូនវិញនៅពេលបញ្ចប់ការជួល បន្ទាប់ពីកាត់ថ្លៃជួល ថ្លៃទឹកភ្លើងដែលមិនទាន់បានបង់ ឬការខូចខាតលើសពីការប្រើប្រាស់ធម្មតា។",
  },
  {
    key: "Water and electricity are billed separately based on actual meter readings at the utility rates in effect for that month, and are due together with the monthly rent.",
    category: "PDF",
    khmer: "ថ្លៃទឹក និងអគ្គិសនីត្រូវគិតដាច់ដោយឡែកតាមលេខកុងទ័រជាក់ស្តែង និងតម្លៃដែលមានសុពលភាពក្នុងខែនោះ ហើយត្រូវបង់ជាមួយថ្លៃជួលប្រចាំខែ។",
  },
  {
    key: "The property is to be used solely as a private residence for the Tenant and the occupants named above. The Tenant may not sublet, assign, or use the premises for any unlawful purpose without the Landlord's prior written consent.",
    category: "PDF",
    khmer: "អចលនទ្រព្យនេះត្រូវប្រើជាលំនៅឋានឯកជនសម្រាប់អ្នកជួល និងអ្នកស្នាក់នៅដែលបានរាយឈ្មោះខាងលើប៉ុណ្ណោះ។ អ្នកជួលមិនអាចជួលបន្ត ផ្ទេរសិទ្ធិ ឬប្រើប្រាស់ទីតាំងសម្រាប់គោលបំណងខុសច្បាប់ ដោយគ្មានការយល់ព្រមជាលាយលក្ខណ៍អក្សរពីម្ចាស់ផ្ទះឡើយ។",
  },
  {
    key: "The Tenant agrees to keep the premises clean and to promptly notify the Landlord of any damage or needed repairs. The Landlord is responsible for maintaining the property in good, habitable condition; the Tenant is responsible for damage caused by their own negligence or misuse.",
    category: "PDF",
    khmer: "អ្នកជួលយល់ព្រមរក្សាទីតាំងឱ្យស្អាត និងជូនដំណឹងដល់ម្ចាស់ផ្ទះភ្លាមៗអំពីការខូចខាត ឬការជួសជុលដែលត្រូវការ។ ម្ចាស់ផ្ទះទទួលខុសត្រូវថែទាំអចលនទ្រព្យឱ្យមានស្ថានភាពល្អសម្រាប់ស្នាក់នៅ ហើយអ្នកជួលទទួលខុសត្រូវចំពោះការខូចខាតដែលបណ្តាលមកពីការធ្វេសប្រហែស ឬការប្រើប្រាស់ខុសរបស់ខ្លួន។",
  },
  {
    key: "Either party may end this agreement at the end of the lease term by giving written notice at least 30 days in advance. Early termination outside the agreed term, or breach of this agreement, may result in forfeiture of some or all of the security deposit as compensation to the Landlord.",
    category: "PDF",
    khmer: "ភាគីណាមួយអាចបញ្ចប់កិច្ចសន្យាដោយជូនដំណឹងជាលាយលក្ខណ៍អក្សរ ៣០ ថ្ងៃជាមុន។ ការបញ្ចប់មុនកំណត់ ឬការរំលោភកិច្ចសន្យា អាចបណ្តាលឱ្យកាត់ប្រាក់កក់ជាសំណងដល់ម្ចាស់ផ្ទះ។",
  },
  {
    key: "This agreement is governed by the applicable laws of the jurisdiction in which the property is located. By signing below, both parties acknowledge that they have read, understood, and agree to all terms of this agreement.",
    category: "PDF",
    khmer: "កិច្ចព្រមព្រៀងនេះស្ថិតក្រោមច្បាប់ដែលអនុវត្តនៅទីតាំងអចលនទ្រព្យ។ តាមរយៈការចុះហត្ថលេខាខាងក្រោម ភាគីទាំងពីរទទួលស្គាល់ថាបានអាន យល់ និងយល់ព្រមតាមលក្ខខណ្ឌទាំងអស់នៃកិច្ចព្រមព្រៀងនេះ។",
  },
];

export const CATALOG_KEYS = new Set(LANGUAGE_CATALOG.map((entry) => entry.key));

// The editor renders exactly one row per catalog entry and submits its key
// alongside the translation, so a repeated key would silently render duplicate
// rows and drop one of them on save. Fail fast instead of losing a phrase.
if (CATALOG_KEYS.size !== LANGUAGE_CATALOG.length) {
  const duplicates = LANGUAGE_CATALOG.map((entry) => entry.key).filter(
    (key, index, keys) => keys.indexOf(key) !== index
  );
  throw new Error(`Duplicate language catalog keys: ${[...new Set(duplicates)].join(", ")}`);
}

export const DEFAULT_KHMER_TRANSLATIONS = Object.fromEntries(
  LANGUAGE_CATALOG.map((entry) => [entry.key, entry.khmer])
) as Record<string, string>;
