<#
.SYNOPSIS
    Removes compiled/build output for RentalHRM to keep the project directory minimal.

.DESCRIPTION
    Deletes generated build artifacts that npm/Next.js/TypeScript recreate automatically:
      - .next            (Next.js/Turbopack build & dev cache output)
      - *.tsbuildinfo     (TypeScript incremental build info)
      - next-env.d.ts     (auto-regenerated by `next dev`/`next build`)

    By default this does NOT remove:
      - node_modules      (installed dependencies; use -IncludeNodeModules to also remove it)
      - prisma/dev.db     (your local database and its data)

.PARAMETER IncludeNodeModules
    Also removes node_modules for a fully minimal checkout. You'll need to run
    `npm install` (or scripts\start.ps1) again before the project will run.

.EXAMPLE
    scripts\clean.ps1
    scripts\clean.ps1 -IncludeNodeModules
#>

param(
    [switch]$IncludeNodeModules
)

$ErrorActionPreference = "Stop"
Set-Location -Path (Join-Path $PSScriptRoot "..")

function Remove-IfExists {
    param([string]$Path)
    if (Test-Path $Path) {
        Write-Host "Removing $Path" -ForegroundColor Yellow
        Remove-Item -Path $Path -Recurse -Force
    }
}

Remove-IfExists ".next"
Remove-IfExists "next-env.d.ts"

Get-ChildItem -Path . -Filter "*.tsbuildinfo" -Recurse -File -ErrorAction SilentlyContinue |
    Where-Object { $_.FullName -notmatch '\\node_modules\\' } |
    ForEach-Object {
        Write-Host "Removing $($_.FullName)" -ForegroundColor Yellow
        Remove-Item -Path $_.FullName -Force
    }

if ($IncludeNodeModules) {
    Remove-IfExists "node_modules"
}

Write-Host "Clean complete." -ForegroundColor Green
